[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 1000000
evm_version = "paris"
via_ir = true

[rpc_endpoints]
rupaya = "${RUPAYA_RPC_URL}"

[etherscan]
rupaya = { key = "", url = "https://scan.rupaya.io/api" }

# Add this section for Blockscout verification
[profile.verification]
rupaya = { chainId = 499, url = "https://scan.rupaya.io/api", verifier = "blockscout" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"
